### PR TITLE
Moves position out of map Update search.css

### PR DESCRIPTION
**Pull request by damianblanck**
Moves position out of map and into white space in bottom right.  Update search.css

### CODE REVIEW

**Comment by mtmail** [comment]
On my large monitor having the debug info on the top or bottom doesn't make much difference. The `-90px` just had a disadvantage if the lines are longer, then content will be cut. Did you want to move it out of focus or is the debug information not useful at all? I could hide it behind a "show mouse position" link or button instead.

**Comment by damianblanck** [comment]
I think the info is usefull. Sometimes I have multiple windows open and don't have nominatim on the full screen. In those cases I found the info important but distracting. 
nominatimmove-map-position

**Comment by lonvia** [comment]
Thanks for the screenshot. I like that change.

**Comment by mtmail** [comment]
The other pull requests (https://github.com/twain47/Nominatim/issues/498) got merged (https://github.com/twain47/Nominatim/commit/cd6dcfa57), so we can close this. Not live on http://nominatim.openstreetmap.org/ yet

**Pull request closed without merging**
