### PR TITLE
use properly cascading make for external make file

### PR DESCRIPTION
**Pull request by lonvia**
If make is called directly then the -j option is not properly propagated. Instead make gives a warning
'No jobserver avilable'.

@melvyn-sopacua I found this recommendation while testing your PR(#629). It works well on Debian. Do you mind testing if it works on BSD as well?

### CODE REVIEW

**Comment by mtmail** [comment]
@lonvia I'll test our centos

**Comment by mtmail** [comment]
works on in our `install-on-centos-7.sh` setup

**Comment by melvyn-sopacua** [comment]
Will do. I ran into it, but forgot about it after disabling jobs locally.

**Comment by melvyn-sopacua** [comment]
I came up with this, trying to be as CMake-conformant as possible:

```diff
diff --git a/module/CMakeLists.txt b/module/CMakeLists.txt
index 318e565..3e913da 100644
--- a/module/CMakeLists.txt
+++ b/module/CMakeLists.txt
@@ -1,10 +1,12 @@
 # just use the pgxs makefile
-ADD_CUSTOM_COMMAND( OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/dummy
-        COMMAND PGXS=${PGXS} PG_CONFIG=${PG_CONFIG} MODSRCDIR=${CMAKE_CURRENT_SOURCE_DIR} $(MAKE) -f ${CMAKE_CURRENT_SOURCE_DIR}/Makefile
+ADD_CUSTOM_TARGET(
+       mod_nominatim ALL
+       DEPENDS nominatim.so
+)
+ADD_CUSTOM_COMMAND(
+        OUTPUT nominatim.so
+        COMMAND PGXS=${PGXS} PG_CONFIG=${PG_CONFIG} MODSRCDIR=${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_MAKE_PROGRAM} -f ${CMAKE_CURRENT_SOURCE_DIR}/Makefile
         COMMENT "Running external makefile ${PGXS}"
-        )
-
-ADD_CUSTOM_TARGET( nominatim_lib ALL
-        DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/dummy
-        )
-
+       MAIN_DEPENDENCY nominatim.c
+        WORKING_DIRECTORY .
+)

```
Got a warning about jobserver not being available, but it builds anyway. It's only one file, there's nothing to parallelize anyway.

**Comment by lonvia** [comment]
Well, the whole point of this PR is to make the jobserver warning go away. Using $(MAKE) does not work on BSD?

**Comment by melvyn-sopacua** [comment]
Yep, works. Local error before, so never mind my PR.

**Pull request merged**
